apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations: {{  - toYaml .Values.service.annotations | nindent 12 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}