replicaCount: 1
resources:
  limits:
    cpu: "100m"
    memory: "124Mi"
  requests:
    cpu: "30m"
    memory: "91Mi"

image:
  repository: int0xicated/s3-exporter
  tag: v.0.2
#  pullSecrets:
  pullPolicy: IfNotPresent

secrets:
  aws_access_key:
    key: AWS_ACCESS_KEY_ID
  aws_secret_key:
    key: AWS_ACCESS_SECRET_KEY
  region_name:
    key: REGION_NAME
  endpoint_url:
    key: ENDPOINT_URL

service:
  type:
  port:

serviceMonitor:
  release: prometheus-operator
  interval: 30s
  scrapeTimeout: 10s
  tls:
    enabled: false