# Number of replicas to deploy
replicaCount: 1

# Resource limits and requests for the container
resources:
  limits:
    cpu: "100m"
    memory: "124Mi"
  requests:
    cpu: "30m"
    memory: "91Mi"

# Image configuration
image:
  repository: int0xicated/s3-exporter
  tag: v.0.2
  # Optional: Secrets for pulling images from private registries
  #  pullSecrets:
  #   - name: regcred-harbor
  # Image pull policy (IfNotPresent, Always, Never)
  pullPolicy: IfNotPresent

# Secrets configuration for environment variables
secrets:
  aws_access_key:
    key: AWS_ACCESS_KEY_ID
  aws_secret_key:
    key: AWS_ACCESS_SECRET_KEY
  region_name:
    key: REGION_NAME
  endpoint_url:
    key: ENDPOINT_URL

# Service configuration
service:
  port: 9000

# ServiceMonitor configuration for Prometheus Operator
serviceMonitor:
  # Release name of Prometheus Operator
  release: prometheus-operator
  interval: 30s
  scrapeTimeout: 10s
  tls:
    enabled: false