apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-exporter
  namespace: monitoring
  labels:
    app: s3-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: s3-exporter
  template:
    metadata:
      labels:
        app: s3-exporter
    spec:
      serviceAccountName: default
      containers:
        - name: s3-exporter
          image: int0xicated/s3-exporter:v.0.2
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          # imagePullSecrets: regcred-harbor
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: "100m"
              memory: "124Mi"
            requests:
              cpu: "30m"
              memory: "96Mi"
          env:
          - name: METRICS_PORT
            value: "9000"
          - name: CONFIG_FILE
            value: |
              buckets:
                - name: $(BUCKET_NAME)
                  aws_access_key_id: $(AWS_ACCESS_KEY_ID)
                  aws_secret_access_key: $(AWS_SECRET_ACCESS_KEY)
                  region_name: $(REGION_NAME)
                  endpoint_url: $(ENDPOINT_URL)