---
apiVersion: v1
kind: Service
metadata:
  name: s3-exporter
  namespace: monitoring
  labels:
    app: s3-exporter
spec:
  selector:
    app: s3-exporter
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP